name: Metrics
on:
    schedule:
        - cron: "0 16 * * *"

    workflow_dispatch:

jobs:
    metrics:
        runs-on: ubuntu-latest

        steps:
            - name: Metrics.LeftPanel
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  filename: metrics.leftpanel.svg
                  output_action: gist
                  committer_gist: ${{ secrets.GIST_ID }}
                  token: ${{ secrets.GIST_PAT }}

                  config_timezone: ${{ vars.CONFIG_TIMEZONE }}
                  config_order: base.header, isocalendar, languages, achievements, stars, habits
                  extras_css: |
                      .items-wrapper > section:not(.column) {
                        padding-top: ${{ vars.PADDING_TOP }}
                      }

                  # commits_authoring: ${{ secrets.COMMITS_AUTHORING }}

                  repositories: ${{ vars.REPOSITORIES }}
                  repositories_forks: ${{ vars.REPOSITORIES_FORKS }}
                  repositories_affiliations: ${{ secrets.REPOSITORIES_AFFILIATIONS }}

                  base: header, activity, community, repositories, metadata
                  base_indepth: yes
                  base_hireable: ${{ vars.PLUGIN_BASE_HIREABLE }}

                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: ${{ vars.PLUGIN_ISOCALENDAR_DURATION }}

                  plugin_languages: yes
                  plugin_languages_limit: ${{ vars.PLUGIN_LANGUAGES_LIMIT }}
                  plugin_languages_threshold: ${{ vars.PLUGIN_LANGUAGES_THRESHOLD }}
                  plugin_languages_other: ${{ vars.PLUGIN_LANGUAGES_OTHER }}
                  plugin_languages_sections: ${{ vars.PLUGIN_LANGUAGES_SECTIONS }}
                  plugin_languages_details: ${{ vars.PLUGIN_LANGUAGES_DETAILS }}
                  plugin_languages_indepth: ${{ vars.PLUGIN_LANGUAGES_INDEPTH }}
                  # plugin_languages_indepth_custom: ${{ secrets.PLUGIN_LANGUAGES_INDEPTH_CUSTOM }}
                  plugin_languages_analysis_timeout: ${{ vars.PLUGIN_LANGUAGES_ANALYSIS_TIMEOUT }}
                  plugin_languages_analysis_timeout_repositories: ${{ vars.PLUGIN_LANGUAGES_ANALYSIS_TIMEOUT_REPOSITORIES }}
                  plugin_languages_recent_load: ${{ vars.PLUGIN_LANGUAGES_RECENT_LOAD }}
                  plugin_languages_recent_days: ${{ vars.PLUGIN_LANGUAGES_RECENT_DAYS }}

                  plugin_achievements: yes
                  plugin_achievements_display: ${{ vars.PLUGIN_ACHIEVEMENTS_DISPLAY }}

                  plugin_stars: yes
                  plugin_stars_limit: ${{ vars.PLUGIN_STARS_LIMIT }}

                  plugin_habits: yes
                  plugin_habits_from: ${{ vars.PLUGIN_HABITS_FROM }}
                  plugin_habits_days: ${{ vars.PLUGIN_HABITS_DAYS }}
                  plugin_habits_charts: ${{ vars.PLUGIN_HABITS_CHARTS }}

            - name: Metrics.RightPanel
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  filename: metrics.rightpanel.svg
                  output_action: gist
                  committer_gist: ${{ secrets.GIST_ID }}
                  token: ${{ secrets.GIST_PAT }}
                  base: ""

                  config_timezone: ${{ vars.CONFIG_TIMEZONE }}
                  config_order: steam, anilist, 16personalities
                  extras_css: |
                      .items-wrapper > section {
                        padding-top: ${{ vars.PADDING_TOP }}
                      }

                  plugin_steam: no
                  plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
                  plugin_steam_user: ${{ secrets.STEAM_USER }}
                  plugin_steam_sections: ${{ vars.PLUGIN_STEAM_SECTIONS }}
                  plugin_steam_games_limit: ${{ vars.PLUGIN_STEAM_GAMES_LIMIT }}
                  plugin_steam_recent_games_limit: ${{ vars.PLUGIN_STEAM_RECENT_GAMES_LIMIT }}
                  plugin_steam_achievements_limit: ${{ vars.PLUGIN_STEAM_ACHIEVEMENTS_LIMIT }}
                  plugin_steam_playtime_threshold: ${{ vars.PLUGIN_STEAM_PLAYTIME_THRESHOLD }}

                  plugin_anilist: yes
                  plugin_anilist_user: ${{ secrets.ANILIST_USER }}
                  plugin_anilist_medias: ${{ vars.PLUGIN_ANILIST_MEDIAS }}
                  plugin_anilist_sections: ${{ vars.PLUGIN_ANILIST_SECTIONS }}
                  plugin_anilist_limit: ${{ vars.PLUGIN_ANILIST_LIMIT }}

                  plugin_16personalities: yes
                  plugin_16personalities_url: https://www.16personalities.com/profiles/${{ secrets.PERSONALITIES_USER }}
