name: Metrics
on:
    schedule:
        - cron: "0 16 * * *"

    workflow_dispatch:

jobs:
    metrics:
        runs-on: ubuntu-latest
        steps:
            # - name: Metrics.Base
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.base.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}

            #       base: header, activity, community, repositories, metadata
            #       base_indepth: yes

            # - name: Metrics.Achievements
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.achievements.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_achievements: yes
            #       plugin_achievements_display: compact

            # - name: Metrics.Activity
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.activity.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_activity: yes
            #       plugin_activity_limit: 5
            #       plugin_activity_days: 28
            #       plugin_activity_visibility: all
            #       plugin_activity_timestamps: yes
            #       plugin_activity_filter: all

            # - name: Metrics.Languages
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.languages.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_languages: yes
            #       plugin_languages_other: yes
            #       plugin_languages_details: percentage, lines, bytes-size

            # - name: Metrics.Isocalendar
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.isocalendar.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_isocalendar: yes
            #       plugin_isocalendar_duration: half-year

            # - name: Metrics.Leetcode
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.leetcode.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_leetcode: yes
            #       plugin_leetcode_user: ${{ secrets.LEETCODE_USER }}

            # - name: Metrics.Notable
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.notable.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_notable: yes
            #       plugin_notable_repositories: no

            # - name: Metrics.Stars
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.stars.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_stars: yes
            #       plugin_stars_limit: 4

            # - name: Metrics.Topics
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.topics.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_topics: yes
            #       plugin_topics_mode: mastered
            #       plugin_topics_sort: activity
            #       plugin_topics_limit: 5

            # - name: Metrics.Skyline
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.skyline.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_skyline: yes
            #       plugin_skyline_frames: 120

            # - name: Metrics.Steam
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.steam.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_steam: yes
            #       plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
            #       plugin_steam_user: ${{ secrets.STEAM_USER }}
            #       plugin_steam_sections: player, recently-played, most-played
            #       plugin_steam_games_limit: 1
            #       plugin_steam_recent_games_limit: 3
            #       plugin_steam_achievements_limit: 2
            #       plugin_steam_playtime_threshold: 0

            # - name: Metrics.Anilist
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.anilist.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_anilist: yes
            #       plugin_anilist_user: ${{ secrets.ANILIST_USER }}
            #       plugin_anilist_medias: manga
            #       plugin_anilist_sections: reading, characters
            #       plugin_anilist_limit: 5

            # - name: Metrics.YouTube
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.youtube.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_music: yes
            #       plugin_music_provider: youtube
            #       plugin_music_token: ${{ secrets.YOUTUBE_COOKIE }}
            #       plugin_music_user: ${{ secrets.YOUTUBE_USER }}
            #       plugin_music_mode: recent
            #       plugin_music_limit: 5

            # - name: Metrics.16Personalities
            #   if: ${{ success() || failure() }}
            #   uses: lowlighter/metrics@latest
            #   with:
            #       filename: metrics.16personalities.svg
            #       output_action: gist
            #       committer_gist: ${{ secrets.GIST_ID }}
            #       token: ${{ secrets.GIST_PAT }}
            #       base: ""

            #       plugin_16personalities: yes
            #       plugin_16personalities_url: https://www.16personalities.com/profiles/${{ secrets.PERSONALITIES_USER }}

            - name: Metrics.LeftPanel
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  filename: metrics.leftpanel.svg
                  output_action: gist
                  committer_gist: ${{ secrets.GIST_ID }}
                  token: ${{ secrets.GIST_PAT }}

                  config_order: base.header, isocalendar, languages, achievements, stars
                  extras_css: |
                      .items-wrapper > section:not([column]) {
                        padding-top: 31px;
                      }

                  base: header, activity, community, repositories, metadata
                  base_indepth: yes

                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year

                  plugin_languages: yes
                  plugin_languages_other: yes
                  plugin_languages_details: percentage, lines, bytes-size

                  plugin_achievements: yes
                  plugin_achievements_display: compact

                  plugin_stars: yes
                  plugin_stars_limit: 4

            - name: Metrics.RightPanel
              if: ${{ success() || failure() }}
              uses: lowlighter/metrics@latest
              with:
                  filename: metrics.leftpanel.svg
                  output_action: gist
                  committer_gist: ${{ secrets.GIST_ID }}
                  token: ${{ secrets.GIST_PAT }}
                  base: ""

                  config_order: steam, anilist, 16personalities
                  extras_css: |
                      .items-wrapper > section {
                        padding-top: 31px;
                      }

                  plugin_steam: yes
                  plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
                  plugin_steam_user: ${{ secrets.STEAM_USER }}
                  plugin_steam_sections: player, recently-played, most-played
                  plugin_steam_games_limit: 1
                  plugin_steam_recent_games_limit: 3
                  plugin_steam_achievements_limit: 2
                  plugin_steam_playtime_threshold: 0

                  plugin_anilist: yes
                  plugin_anilist_user: ${{ secrets.ANILIST_USER }}
                  plugin_anilist_medias: manga
                  plugin_anilist_sections: reading, characters
                  plugin_anilist_limit: 5

                  plugin_16personalities: yes
                  plugin_16personalities_url: https://www.16personalities.com/profiles/${{ secrets.PERSONALITIES_USER }}
