
name: Metrics
on:
    schedule:
        - cron: "0 16 * * *"

    workflow_dispatch:

jobs:
    metrics:
        runs-on: ubuntu-latest
        steps:

            - name: Introduction
                if: ${{ success() || failure() }}
                uses: lowlighter/metrics@latest
                with:
                    filename: introduction.svg
                    output_action: gist
                    committer_gist: ${{ secrets.GITHUB_ACTOR }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    plugin_introduction: yes
                    plugin_introduction_title: "Today I bought mineral water and drank it. I thought it tasted better than tap water. I don't know, but it was good."

            - name: General
                if: ${{ success() || failure() }}
                uses: lowlighter/metrics@latest
                with:
                    filename: general.svg
                    output_action: gist
                    committer_gist: ${{ secrets.GITHUB_ACTOR }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    config_order: isocalendar, languages
                    plugin_isocalendar: yes
                    plugin_isocalendar_duration: half-year

                    plugin_languages: yes

            - name: Entertainment
                if: ${{ success() || failure() }}
                uses: lowlighter/metrics@latest
                with:
                    filename: entertainment.svg
                    output_action: gist
                    committer_gist: ${{ secrets.GITHUB_ACTOR }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    config_order: anilist, music
                    plugin_anilist: yes
                    plugin_anilist_user: ${{ secrets.ANILIST_USER }}

                    plugin_music: yes
                    plugin_music_provider:
                    plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
                    plugin_music_user: ${{ secrets.SPOTIFY_USER }}

                    plugin_steam: yes
                    plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
                    plugin_steam_user: ${{ secrets.STEAM_USER }}

                    plugin_16personalities: yes
                    plugin_16personalities_url: https://www.16personalities.com/profiles/${{ secrets.PERSONALITIES_USER }}
